server:
  port: 9006

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db?useSSL=false&serverTimezone=UTC
    username: root
    password: LG101799
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
  mail:
    host: smtp.qq.com
    port: 465
    username: 3411426617@qq.com
    password: bojwesxvnloecjdi
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  config:
    import: "optional:configserver:"  # 关键修复！必须添加！
  application:
    name: notification-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    register-with-eureka: true    # 启用注册
    fetch-registry: true          # 获取注册表
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka 地址