server:
  port: 9409
spring:
  application:
    name: oss-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:"  # 关键修复！必须添加！
oss:
  encryption:
    current-key-id: k2025
    key-retention-days: 365
    keys:
      k2025: "heSu75QlSY7yG2i1qZdFCg=="
      k2026: "GaaDwO8zw7l9bXgrvKTMCg=="
      k2027: "kksqqi/N6Gt1f57fjI83Tg=="
  storage:
    type: local # aliyun or local
  # 阿里云配置
  aliyun:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRJLT1Lr5fHLycXq9YW
    access-key-secret: o5BT9TkluD3esZIYaChrk11F1t8Lhk
    bucket-name: doubao-1017
  # 本地存储配置
  local:
    storage-path: /home/java/doubao/file/uploads
    base-url: http://http://49.233.21.30/api/public/oss/files
    default-avatar: defaultAvatar.png
    aes-key: doubao