server:
  port: 9004

spring:
  stream:
    bindings:
      orderCreated-out-0:
        destination: payment.success
    rabbit:
      bindings:
        orderCreated-out-0:
          producer:
            routing-key-expression: ''
    default-binder: rabbit
  config:
    import: "optional:configserver:"  # 关键修复！必须添加！
  application:
    name: payment-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?useSSL=false&serverTimezone=UTC
    username: root
    password: LG101799
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  redisson:
    config: |
      singleServerConfig:
        address: "redis://127.0.0.1:6379"
        connectionMinimumIdleSize: 5
        idleConnectionTimeout: 30000
        connectTimeout: 5000   # 连接超时设为5秒
        timeout: 3000
        retryAttempts: 3      # 重试次数
        retryInterval: 1000    # 重试间隔

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    register-with-eureka: true    # 启用注册
    fetch-registry: true          # 获取注册表
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka 地址
