server:
  port: 9400

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

eureka:
  client:
    register-with-eureka: true    # 启用注册
    fetch-registry: true          # 获取注册表
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka 地址