server:
  port: 9002

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  redisson:
    config: |
      singleServerConfig:
        address: "redis://127.0.0.1:6379"
        connectionMinimumIdleSize: 5
        idleConnectionTimeout: 30000
        connectTimeout: 5000   # 连接超时设为5秒
        timeout: 3000
        retryAttempts: 3      # 重试次数
        retryInterval: 1000    # 重试间隔

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka