server:
  port: 9401
spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:mysql://localhost:3306/quote_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Lg101799.
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  config:
    import: "optional:configserver:"  # 关键修复！必须添加！