server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config-repo/  # 使用资源目录下的配置

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    register-with-eureka: true    # 启用注册
    fetch-registry: true          # 获取注册表
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka 地址
  instance:
    hostname: ${HOSTNAME:${spring.application.name}}
    prefer-ip-address: false # 禁用IP注册