spring:
  application:
    name: view-count-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    # Nacos服务器地址
  config:
    import:
      - nacos:view-count-service-dev.yaml   # 从Nacos加载配置文件