server:
  port: 9100
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: quote_db
      username: root
      password: 123456
      authentication-database: admin
  application:
    name: quote-service
  datasource:
    url: jdbc:mysql://localhost:3306/quote_db?useSSL=false&serverTimezone=UTC
    username: root
    password: LG101799
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  config:
    import: "optional:configserver:"  # 关键修复！必须添加！